type SKUSpecificationField {
  name: String!
  originalName: String
}

type SKUSpecificationValue {
  name: String!
  originalName: String
}

type SkuSpecification {
  field: SKUSpecificationField!
  values: [SKUSpecificationValue]!
}

type ItemImage {
  imageId: String!
  imageUrl: String!
}

type Variations {
  name: String!
  values: [String!]
}

type CommertialOffer {
  Price: Float!
  ListPrice: Float!
  AvailableQuantity: Int!
}

type Seller {
  sellerDefault: Boolean!
  sellerId: String
  sellerName: String!
  commertialOffer: CommertialOffer
}

type Items {
  itemId: String!
  name: String!
  images: [ItemImage]
  variations: [Variations!]
  sellers: [Seller!]
}

type StoreProduct {
  items: [Items!]
  skuSpecifications: [SkuSpecification!]
}

type Query {
  shipping(
    postalCode: String
    geoCoordinates: [String]
    country: String
    items: [ShippingItem]
  ): ShippingData
}
